# Generated by Django 4.2.18 on 2025-01-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('piece_per_box', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item_date', models.DateField()),
                ('qty_box', models.IntegerField(default=0)),
                ('qty_piece', models.IntegerField(default=0)),
                ('time', models.TimeField()),
                ('total_qty', models.IntegerField(editable=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.item')),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
